import type { Metadata } from 'next'
import { Noto_Sans_KR, Black_Han_Sans } from 'next/font/google'
import { AboutDetailSkillModal } from '../layers/widgets/modal/about-detail-skill-modal'
import './globals.css'

const noto_sans_kr = Noto_Sans_KR({
  subsets: ['latin'],
  display: 'swap',
  fallback: ['sans-serif'],
  variable: '--font-sans-kr',
})

const black_han_sans = Black_Han_Sans({
  subsets: ['latin'],
  weight: '400',
  fallback: ['sans-serif'],
  variable: '--font-black-han-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ko"
      className={`${noto_sans_kr.variable} ${black_han_sans.variable}`}
    >
      <body>
        {/* TODO: 나중에 ModalProvider로 바꿀 필요성 있음 */}
        <AboutDetailSkillModal />
        {children}
      </body>
    </html>
  )
}
